### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by RezaNoviansyah** [nmarus/node-ews#102]
can you help me i got error
(node:15115) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pipe listeners added. Use emitter.setMaxListeners() to increase limit
Potentially unhandled rejection [3] Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://webmail.lintasarta.co.id/owa/auth/errorFE.aspx?httpCode=500
    at Redirect.onResponse (/home/rezanoviansyah/NODE_JS/node_modules/request/lib/redirect.js:98:27)
    at Request.onRequestResponse (/home/rezanoviansyah/NODE_JS/node_modules/request/request.js:917:22)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:607:20)

**Comment by timmy-lee** [comment]
Hi all, I am also facing this exact issue, but with an account that's on a hybrid setup.
