### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by juan-ruiz** [nmarus/node-ews#33]
I was trying to send a mail using node-ews but i get this exception when i try to run the call:

```
Uncaught Exception:
RangeError: Maximum call stack size exceeded
    at WSDL.findChildSchemaObject (/home/juan/workspace/persoMachine/node_modules/soap/lib/wsdl.js:1902:48)
    at WSDL.findChildSchemaObject (/home/juan/workspace/persoMachine/node_modules/soap/lib/wsdl.js:1951:20)
    at WSDL.findChildSchemaObject (/home/juan/workspace/persoMachine/node_modules/soap/lib/wsdl.js:1951:20)
    at WSDL.findChildSchemaObject (/home/juan/workspace/persoMachine/node_modules/soap/lib/wsdl.js:1945:19)
    at WSDL.findChildSchemaObject (/home/juan/workspace/persoMachine/node_modules/soap/lib/wsdl.js:1951:20)
    at WSDL.findChildSchemaObject (/home/juan/workspace/persoMachine/node_modules/soap/lib/wsdl.js:1951:20)
    at WSDL.findChildSchemaObject (/home/juan/workspace/persoMachine/node_modules/soap/lib/wsdl.js:1945:19)
    at WSDL.findChildSchemaObject (/home/juan/workspace/persoMachine/node_modules/soap/lib/wsdl.js:1951:20)
    at WSDL.findChildSchemaObject (/home/juan/workspace/persoMachine/node_modules/soap/lib/wsdl.js:1951:20)
    at WSDL.findChildSchemaObject (/home/juan/workspace/persoMachine/node_modules/soap/lib/wsdl.js:1945:19)
```

....

  ```
    const ews = new EWS(username, password, host, options);
      var ewsSoapHeader = {
      't:RequestServerVersion': {
      attributes: {
      Version: "Exchange2010"
        }
       }
      };
      ewsFunction = "CreateItem";
      ewsArgs = {
        "attributes" : {
          "MessageDisposition" : "SendAndSaveCopy"
        },
        "SavedItemFolderId" : {
          "DistinguishedFolderId" : {
            "attributes" : {
              "Id" : "sentitems"
            }
          }
        },
        "Items" : {
          "Message" : {
            "Subject" : "[Code",
            "Body" : "Test",
            "ToRecipients" : {
              "Mailbox" : {
                "EmailAddress" : "ruizvilla@gmail.com"
              }
            }
          }
        }
      };

      ews.run(ewsFunction, ewsArgs, ewsSoapHeader)
        .then(result => {
         console.log("WE FUCKING DID IT");
          
        })
        .catch(err => {
         

        });

    });
```

I read about a simmilar incident on this issue-tracker, but attending to the resolution notes (that stated that if it happened again, one should open a new ticket altogether) i am opening this issue,

Thanks a lot! this is an amazing library :)

**Comment by nmarus** [comment]
Can you review #17 and see if the fix mentioned there with the node-soap library fixes this for you?

**Comment by juan-ruiz** [comment]
it was indeed a duplicated, feeling so smart right now

**Comment by nmarus** [comment]
No worries. Ive been hacking away on node soap all day to try and see a way around this with a custom fork.
